"""
captions.py — write two caption options for the finished deck.

The producer never picks the caption for you; it drafts two distinct options
(one punchy, one story-led) and lets you choose. Both are generated by Claude
from the topic and the approved outline, and fall back to simple offline drafts
when no API key is set.
"""
from __future__ import annotations

import json

from config import Settings

from .brand import Brand

_CAPTIONS_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "captions": {
            "type": "array",
            "items": {"type": "string"},
        }
    },
    "required": ["captions"],
}


def write_captions(topic: str, slides: list[dict], brand: Brand,
                   settings: Settings) -> list[str]:
    """Return exactly two caption options for the deck."""
    if not settings.has_anthropic:
        return _offline_captions(topic, brand)

    try:
        import anthropic
    except ImportError:  # pragma: no cover
        return _offline_captions(topic, brand)

    client = anthropic.Anthropic()
    summary = " / ".join(
        s.get("headline") or s.get("stat") or s.get("cta_text") or s.get("type", "")
        for s in slides
    )
    resp = client.messages.create(
        model=settings.model,
        max_tokens=1200,
        system=(
            "You write Instagram captions in a clear, natural voice — no hashtag "
            "spam, no AI-ish phrasing. Give exactly two distinct options: one "
            "short and punchy, one that opens with a one-line story or hook. End "
            "each with a soft call to action."
        ),
        output_config={"format": {"type": "json_schema", "schema": _CAPTIONS_SCHEMA}},
        messages=[{
            "role": "user",
            "content": (
                f"Topic: {topic}\nBrand handle: {brand.handle}\n"
                f"Slides: {summary}\n\nReturn two caption options."
            ),
        }],
    )
    text = _text_of(resp)
    try:
        captions = json.loads(text).get("captions", [])
    except (json.JSONDecodeError, AttributeError):
        captions = []
    captions = [c for c in captions if c.strip()][:2]
    return captions or _offline_captions(topic, brand)


def _text_of(resp) -> str:
    parts = [b.text for b in getattr(resp, "content", []) if getattr(b, "type", "") == "text"]
    return "\n".join(parts).strip()


def _offline_captions(topic: str, brand: Brand) -> list[str]:
    return [
        f"Everything you need to know about {topic}, in one swipe. "
        f"Save this and follow {brand.handle} for more.",
        f"I used to get {topic} completely wrong. Here's what finally clicked — "
        f"swipe through, then tell me which slide hit hardest.",
    ]
